### ISSUE TITLE
error - Provided runtime "edge" is not supported. Please leave it empty or choose one of: experimental-edge, nodejs

### ISSUE THREAD

**Issue by akdeb** [Nutlope/twitterbio#19]
Do you know how to fix this error: "error - Provided runtime "edge" is not supported. Please leave it empty or choose one of: experimental-edge, nodejs"?

I see this on my server and I am on Next.js v12.3.0. My route is defined in pages/api/*

**Comment by dvaJi** [comment]
The error is because you are using Next.js 12 and the runtime "edge" is experimental in that version. To resolve the issue, you can upgrade to Next.js 13 or modify the runtime "edge" (in pages/api/generate.ts) to "experimental-edge".

**Comment by akdeb** [comment]
That fixed it thanks @dvaJi! 🚀
