### ISSUE TITLE
Twitter has a limit of 160 character

### ISSUE THREAD

**Issue by bhuynhdev** [Nutlope/twitterbio#3]
This is such an amazing tool I must say, but Twitter has a 160 character limit and sometimes the output is longer.

But I'm not sure if this should be included in the product (i.e if the product is only meant to be for inspiration)

**Comment by Nutlope** [comment]
Unfortunately tried to get this to work but GPT-3 doesn't understand the 160 character max.

**Comment by akdeb** [comment]
you can also play around with temperature in your API if you want to account for less randomness and more rigidity in responses https://algowriting.medium.com/gpt-3-temperature-setting-101-41200ff0d0be
