### ISSUE TITLE
I found hastag in the result

### ISSUE THREAD

**Issue by yusufmalikul** [Nutlope/twitterbio#4]
>{"prompt":"Generate 2 funny twitter bios with no hashtags and clearly labeled \"1.\" and \"2.\". Make sure there is a joke in there and it's a little ridiculous. Make sure each generated bio is at max 20 words and base it on this context: Sharing my thoughts on technology and life."}

```
 A tech enthusiast trying to make sense of this crazy world. #WishMeLuck
```

**Comment by Nutlope** [comment]
It doesn't work 100% of the time – makes some mistakes :)

**Comment by yusufmalikul** [comment]
I see. ok :)
