### ISSUE TITLE
Stream the OpenAI Completion

### ISSUE THREAD

**Issue by saliksik** [Nutlope/twitterbio#5]
Good Day, Sir!

How can I stream the OpenAI Completion?

I tried it on my end, but I can't make it.

Reference:

https://www.beskar.co/blog/streaming-openai-completions-vercel-edge

**Comment by Nutlope** [comment]
Just closing this project should help you stream the completion. What are you struggling with specifically?

**Comment by Nutlope** [comment]
Closing for now, feel free to re-open or DM me on twitter if you have questions.
